# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPTAwebtest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pTAwebtest1(self):
    # Test name: PTA web test 1
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.pta.gov.pk/")
    # 2 | setWindowSize | 1050x708 | 
    self.driver.set_window_size(1050, 708)
    # 3 | runScript | window.scrollTo(0,2298) | 
    self.driver.execute_script("window.scrollTo(0,2298)")
    # 4 | runScript | window.scrollTo(0,2343) | 
    self.driver.execute_script("window.scrollTo(0,2343)")
    # 5 | runScript | window.scrollTo(0,4236) | 
    self.driver.execute_script("window.scrollTo(0,4236)")
    # 6 | click | css=.md\3Atext-left > .transition-colors > .text-lg | 
    self.driver.find_element(By.CSS_SELECTOR, ".md\\3Atext-left > .transition-colors > .text-lg").click()
  
